#### Neural Nettworks

In [4]:
import torch
import torch.nn as nn

In [5]:
input_layer = torch.rand(10)

w1 = torch.rand(10, 20)
w2 = torch.rand(20, 20)
w3 = torch.rand(20, 4)

h1 = torch.matmul(input_layer, w1)
h2 = torch.matmul(h1, w2)
output_layer = torch.matmul(h2, w3)

print(output_layer)

tensor([341.5610, 304.6591, 270.2589, 283.7715])


#### OOP Neural Network

In [6]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(10, 20)
        self.fc2 = nn.Linear(20, 20)
        self.output = nn.Linear(20, 4)
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.output(x)
        return x

In [7]:
net = Net()
result = net(input_layer)

In [8]:
result

tensor([ 0.0274, -0.1448,  0.0011, -0.1144], grad_fn=<ViewBackward0>)

In [9]:
input_layer = torch.tensor([2., 1.])
weight_1 = torch.tensor([[0.45, 0.32], [-0.12, 0.29]])
hidden_layer = torch.matmul(input_layer, weight_1)
weight_2 = torch.tensor([[0.48, -0.12], [0.64, 0.91]])
output_layer = torch.matmul(hidden_layer, weight_2)
print(output_layer)

tensor([0.9696, 0.7527])


In [10]:
input_layer = torch.tensor([2., 1.])
weight_1 = torch.tensor([[0.45, 0.32], [-0.12, 0.29]])
weight_2 = torch.tensor([[0.48, -0.12], [0.64, 0.91]])
weight = torch.matmul(weight_1, weight_2)
output_layer = torch.matmul(input_layer, weight)
print(output_layer)
print(weight)

tensor([0.9696, 0.7527])
tensor([[0.4208, 0.2372],
        [0.1280, 0.2783]])


In [12]:
relu = nn.ReLU()
tensor1 = torch.tensor([2., -4.])
print(relu(tensor1))
tensor2 = torch.tensor([[2., -4.], [1.2, 0.]])
print(relu(tensor2))

tensor([2., 0.])
tensor([[2.0000, 0.0000],
        [1.2000, 0.0000]])


#### CE loss in pyTorch