In [3]:
import torch
import numpy as np

In [4]:
torch.tensor([[2, 3, 5], [1, 2, 9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [5]:
np.array([[2, 3, 5], [1, 2, 9]])

array([[2, 3, 5],
       [1, 2, 9]])

#### random matrices

In [6]:
torch.rand(2, 2)

tensor([[0.1439, 0.5225],
        [0.2509, 0.8332]])

In [7]:
np.random.rand(2,2)

array([[0.90051564, 0.43081047],
       [0.20232469, 0.82030371]])

#### shape

In [8]:
a = torch.rand((3,5))

In [9]:
a.shape

torch.Size([3, 5])

In [10]:
a = np.random.randn(3, 5)

In [11]:
a.shape

(3, 5)

#### Matrix Multiplication

a = torch.rand(2, 2)
b = torch.rand(2, 2)

In [13]:
torch.matmul(a,b)

tensor([[0.3079, 0.4036],
        [0.7007, 0.8585]])

In [15]:
a = np.random.rand(2,2)
b = np.random.rand(2,2)

In [16]:
np.dot(a,b)

array([[1.19707128, 0.86919457],
       [0.71560889, 0.27563991]])

#### ones and zeros

In [18]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [19]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [20]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

#### element wise operation

In [22]:
a * b

array([[0.73800226, 0.19410595],
       [0.38790017, 0.11162595]])

### Forward Propagation

In [23]:
a = torch.tensor([2])
b = torch.tensor([-4])
c = torch.tensor([-2])
d = torch.tensor([2])

In [25]:
e = a + b
f = c * d

In [26]:
g = e * f

In [27]:
print(e, f,g)

tensor([-2]) tensor([-4]) tensor([8])


#### Backpropagation in pyTorch

In [28]:
x = torch.tensor(-3., requires_grad=True)
y = torch.tensor(5., requires_grad=True)
z = torch.tensor(-2., requires_grad=True)

In [29]:
q = x + y
f = q * z

In [30]:
f.backward()

In [33]:
print("Gradient of z is: " + str(z.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of x is: " + str(x.grad))

Gradient of z is: tensor(2.)
Gradient of y is: tensor(-2.)
Gradient of x is: tensor(-2.)
